# Generated by Django 5.1.7 on 2025-03-15 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='drive_unit',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='gearbox',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='volume',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='sale',
            name='car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='main.car'),
        ),
        migrations.AddField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='main.client'),
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
